language: node_js
#services: mongodb

matrix:
  fast_finish: true
  
branches:
  only:
    - master
  
cache:
  - apt
  - npm
  
script:
  - chmod u+x travis.sh
  - ./travis.sh


#after_success:
#  - sleep 5; curl 0.0.0.0:3000
